pull_request_rules:
  - name: automatic merge
    conditions:
      - "label=ready-to-merge"    # Check if the PR has a specific label
    actions:
      merge:
        method: squash           # Merge method: merge, squash, or rebase
